# Generated by Django 3.2 on 2023-07-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='News header')),
                ('preamble', models.CharField(max_length=1000, verbose_name='Introduction')),
                ('body', models.TextField(verbose_name='Content')),
                ('body_as_markdown', models.BooleanField(default=False, verbose_name='Markdown option')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Last change date')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'Many news',
                'ordering': ('-created_at',),
            },
        ),
    ]
