# Generated by Django 3.2 on 2023-07-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20230712_2056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lessons',
            new_name='Lesson',
        ),
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Last change date')),
                ('name_first', models.CharField(max_length=128, verbose_name='Name')),
                ('name_last', models.CharField(max_length=128, verbose_name='Surname')),
                ('day_birth', models.DateField(verbose_name='Birth date')),
                ('deleted', models.BooleanField(default=False)),
                ('course', models.ManyToManyField(to='mainapp.Course')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
