# Generated by Django 3.2 on 2023-07-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20230712_2057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseTeacher',
            new_name='CourseTeachers',
        ),
    ]
