# Generated by Django 3.2 on 2023-07-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_data_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseteachers',
            options={'verbose_name': 'Course teacher', 'verbose_name_plural': 'Course teachers'},
        ),
    ]
